Deployment_Project/force-app/main/default/objects/DeveloperG__c/DeveloperG__c.object-meta.xml
<CustomObject>
    <description>This object stores all the developers of an organization.</description>
    <label>DeveloperG</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DeveloperGs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Deployment_Project/force-app/main/default/objects/DeveloperG__c/fields/Organization__c.field-meta.xml
<CustomField>
    <fullName>Organization__c</fullName>
    <description>This field is used to store the name of the organization that a developer is affiliated with.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Organization</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

Deployment_Project/force-app/main/default/classes/OnDeveloperCreationHandler.cls
public with sharing class OnDeveloperCreationHandler {
    public static void process(List<DeveloperG__c> devList){
        if(Schema.sObjectType.DeveloperG__c.fields.organization__c.isUpdateable()){
            Map<String, Schema.sObjectField> devFieldMap = Schema.sObjectType.DeveloperG__c.fields.getMap();
            System.debug(devFieldMap);
            if(devFieldMap.containsKey('Organization__c')){
                Schema.sObjectField org = devFieldMap.get('Organization__c');
                for(DeveloperG__c dev : devList){
                    if(dev.get(org) == null){
                     	dev.put(org, 'Mirketa');   
                    }
                }
            }
        }else{
            System.debug('Exception: Organization__c Field in DeveloperG__c Object is not editable!!!');
        }
    }
}